/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Coupon {
  'code' : string,
  'description' : string,
  'discountPercent' : bigint,
  'isActive' : boolean,
}
export interface Feedback {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'email' : string,
  'message' : string,
}
export interface Product {
  'id' : bigint,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
  'isActive' : boolean,
  'specs' : ProductSpecs,
  'imageUrl' : string,
  'category' : string,
  'price' : bigint,
  'condition' : string,
}
export interface ProductSpecs {
  'ram' : string,
  'fingerPrintWorking' : boolean,
  'camerasWorking' : boolean,
  'speakerWorking' : boolean,
  'storage' : string,
  'batteryReplaced' : boolean,
  'backPanelReplaced' : boolean,
  'chargingSpeed' : string,
  'batteryHealth' : bigint,
  'wifiWorking' : boolean,
  'touchWorking' : boolean,
  'bluetoothWorking' : boolean,
  'micWorking' : boolean,
  'batteryCapacity' : string,
  'screenReplaced' : boolean,
}
export interface _SERVICE {
  'addCoupon' : ActorMethod<[Coupon], undefined>,
  'addProduct' : ActorMethod<[Product], bigint>,
  'deleteCoupon' : ActorMethod<[string], undefined>,
  'deleteProduct' : ActorMethod<[bigint], undefined>,
  'getAllCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAllFeedback' : ActorMethod<[], Array<Feedback>>,
  'getAllProducts' : ActorMethod<[], Array<Product>>,
  'getProduct' : ActorMethod<[bigint], Product>,
  'getProductsByCategory' : ActorMethod<[string], Array<Product>>,
  'submitFeedback' : ActorMethod<[string, string, string], bigint>,
  'updateCoupon' : ActorMethod<[string, Coupon], undefined>,
  'updateProduct' : ActorMethod<[bigint, Product], undefined>,
  'validateCoupon' : ActorMethod<[string], [] | [bigint]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];