/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Coupon = IDL.Record({
  'code' : IDL.Text,
  'description' : IDL.Text,
  'discountPercent' : IDL.Nat,
  'isActive' : IDL.Bool,
});
export const ProductSpecs = IDL.Record({
  'ram' : IDL.Text,
  'fingerPrintWorking' : IDL.Bool,
  'camerasWorking' : IDL.Bool,
  'speakerWorking' : IDL.Bool,
  'storage' : IDL.Text,
  'batteryReplaced' : IDL.Bool,
  'backPanelReplaced' : IDL.Bool,
  'chargingSpeed' : IDL.Text,
  'batteryHealth' : IDL.Nat,
  'wifiWorking' : IDL.Bool,
  'touchWorking' : IDL.Bool,
  'bluetoothWorking' : IDL.Bool,
  'micWorking' : IDL.Bool,
  'batteryCapacity' : IDL.Text,
  'screenReplaced' : IDL.Bool,
});
export const Product = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
  'isActive' : IDL.Bool,
  'specs' : ProductSpecs,
  'imageUrl' : IDL.Text,
  'category' : IDL.Text,
  'price' : IDL.Nat,
  'condition' : IDL.Text,
});
export const Feedback = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'email' : IDL.Text,
  'message' : IDL.Text,
});

export const idlService = IDL.Service({
  'addCoupon' : IDL.Func([Coupon], [], []),
  'addProduct' : IDL.Func([Product], [IDL.Nat], []),
  'deleteCoupon' : IDL.Func([IDL.Text], [], []),
  'deleteProduct' : IDL.Func([IDL.Nat], [], []),
  'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
  'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
  'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
  'getProductsByCategory' : IDL.Func([IDL.Text], [IDL.Vec(Product)], ['query']),
  'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'updateCoupon' : IDL.Func([IDL.Text, Coupon], [], []),
  'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
  'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Coupon = IDL.Record({
    'code' : IDL.Text,
    'description' : IDL.Text,
    'discountPercent' : IDL.Nat,
    'isActive' : IDL.Bool,
  });
  const ProductSpecs = IDL.Record({
    'ram' : IDL.Text,
    'fingerPrintWorking' : IDL.Bool,
    'camerasWorking' : IDL.Bool,
    'speakerWorking' : IDL.Bool,
    'storage' : IDL.Text,
    'batteryReplaced' : IDL.Bool,
    'backPanelReplaced' : IDL.Bool,
    'chargingSpeed' : IDL.Text,
    'batteryHealth' : IDL.Nat,
    'wifiWorking' : IDL.Bool,
    'touchWorking' : IDL.Bool,
    'bluetoothWorking' : IDL.Bool,
    'micWorking' : IDL.Bool,
    'batteryCapacity' : IDL.Text,
    'screenReplaced' : IDL.Bool,
  });
  const Product = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
    'isActive' : IDL.Bool,
    'specs' : ProductSpecs,
    'imageUrl' : IDL.Text,
    'category' : IDL.Text,
    'price' : IDL.Nat,
    'condition' : IDL.Text,
  });
  const Feedback = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'email' : IDL.Text,
    'message' : IDL.Text,
  });
  
  return IDL.Service({
    'addCoupon' : IDL.Func([Coupon], [], []),
    'addProduct' : IDL.Func([Product], [IDL.Nat], []),
    'deleteCoupon' : IDL.Func([IDL.Text], [], []),
    'deleteProduct' : IDL.Func([IDL.Nat], [], []),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAllFeedback' : IDL.Func([], [IDL.Vec(Feedback)], ['query']),
    'getAllProducts' : IDL.Func([], [IDL.Vec(Product)], ['query']),
    'getProduct' : IDL.Func([IDL.Nat], [Product], ['query']),
    'getProductsByCategory' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Product)],
        ['query'],
      ),
    'submitFeedback' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateCoupon' : IDL.Func([IDL.Text, Coupon], [], []),
    'updateProduct' : IDL.Func([IDL.Nat, Product], [], []),
    'validateCoupon' : IDL.Func([IDL.Text], [IDL.Opt(IDL.Nat)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };